name: Development

on: [push, pull_request]
  
jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps: 
      - name: "checkout repository"
        uses: actions/checkout@main
      
      - name: Run test
        run: go mod tidy
          
      - name: Build the project
        run: |
          go build -v -o ./queue ./queue

      - name: Start the gRPC server
        run: |
          ./queue/queue &
          sleep 5
          
      - name: dispatcher integration test
        run: go test -v ./dispatcher/... -run Integration