name: Development

on: [push, pull_request]
  
jobs:
  test:
    name: Unit test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps: 
      - name: "checkout repository"
        uses: actions/checkout@main
          
      - name: echo stuff
        run: |
          echo $PATH
          echo $GOROOT
          echo $GOPATH
          
      - name: "ls"
        run: ls -a

      # - name: Change directory to queue
      #   run: cd queue

      # - name: "ls"
      #   run: ls -a
          
      - name: Build the project
        run: |
          go build -v -o queue queue

      - name: Start the gRPC server
        run: |
          ./queue/queue &
          sleep 5
          
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.17'
        working-directory: ./dispatcher

      - name: Run test
        run: |
          cd ./dispatcher
          ls -a
          go get -v ./...
          
        # go test -v ./dispatcher/... -run Integration